runtime : python310
instance_class: F4_1G 

automatic_scaling:
  target_cpu_utilization: 0.9 #Set cpu to work with 90% 
  min_instances: 1
  max_instances: 10
  min_pending_latency: automatic
  max_pending_latency: automatic

handlers:
  # This configures Google App Engine to serve the files in the app's static
  # directory.
- url: /static
  static_dir: static

  # This handler routes all requests not caught above to your main app. It is
  # required when static routes are defined, but can be omitted (along with
  # the entire handlers section) when there are no static files defined.
- url: /.*
  script: auto